# (Required) Mirror directions
directions:
  - from: [-1001, -1002, -1003]
    to: [-100203]
    # Overwrite global settings
    disable_edit: false
    disable_delete: false
    mode: forward
    # Overwrite global filters
    filters:
      - UrlMessageFilter:
          blacklist: !!set
            ? t.me
      - KeywordReplaceFilter:
          keywords:
            "google.com": "bing.com"
          regex: false # treat keywords as plain text
      - SkipWithKeywordsFilter:
          keywords: !!set
            ? "stopword"
          regex: true # treat keywords as regex expr
